# Correlation between pandas and numpy

In [1]:
import pandas as pd
import numpy as np

## Reading the file

In [22]:
df = pd.read_csv("pokemon_data.csv")
df = df.drop(columns=["#"])
df.head(5)

Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0              Bulbasaur  Grass  Poison  45      49       49       65   
1                Ivysaur  Grass  Poison  60      62       63       80   
2               Venusaur  Grass  Poison  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [12]:
a = np.array(df["HP"])
a.reshape(2,400)
print(a[0:9])
print(a.size)

[45 60 80 80 39 58 78 78 78]
800


In [14]:
b = np.array(df['Attack'])
b.reshape(2,400)
print(b[0:9])
b[0:9]

[ 49  62  82 100  52  64  84 130 104]


array([ 49,  62,  82, 100,  52,  64,  84, 130, 104])

In [18]:
product = a*b
product

array([ 2205,  3720,  6560,  8000,  2028,  3712,  6552, 10140,  8112,
        2112,  3717,  6557,  8137,  1350,  1000,  2700,  1400,  1125,
        5850,  9750,  1800,  3780,  6640,  6640,  1680,  4455,  2400,
        5850,  2100,  5100,  1925,  5400,  3750,  7500,  2585,  4340,
        8280,  2622,  4392,  8262,  3150,  6650,  1558,  5548,  5175,
        9800,  1800,  6000,  2250,  3900,  6000,  2450,  5700,  3300,
        4550,   550,  2800,  1800,  4550,  2600,  6560,  3200,  6825,
        3850,  9900,  2000,  4225,  8550,   500,  1400,  2750,  2750,
        5600,  8000, 11700,  3750,  5850,  8400,  1600,  5600,  3200,
        5225,  9600,  4250,  6500,  5850,  7125,  7125,   875,  3000,
        3380,  2975,  6600,  2925,  6300,  6400, 11025,  1950,  4750,
        1050,  2250,  3900,  3900,  1575,  2880,  6205,  3150,  7150,
        1200,  3000,  2400,  9025,  2500,  4800,  6000,  5250,  4950,
        2600,  5850,  6800, 13650,  1250,  3575,  9975, 13125,  1200,
        3575,  3015,