In [1]:
import numpy as np

In [17]:
# Create a matrix
a = np.random.randint(1,5, size= (10,10))
print(a)
print(a.shape)

[[1 2 3 4 1 4 4 3 1 3]
 [2 2 4 4 2 4 4 1 2 1]
 [2 3 3 2 1 2 1 4 2 2]
 [1 3 4 4 1 1 1 2 3 3]
 [2 2 1 3 3 1 1 1 1 4]
 [2 3 2 2 1 3 3 2 2 3]
 [2 4 1 3 1 2 4 2 2 1]
 [3 2 3 1 3 1 1 2 3 3]
 [2 3 4 4 1 2 2 1 3 3]
 [3 3 4 3 2 1 3 1 1 2]]
(10, 10)


In [18]:
a[a[:, 2] == 3]

array([[1, 2, 3, 4, 1, 4, 4, 3, 1, 3],
       [2, 3, 3, 2, 1, 2, 1, 4, 2, 2],
       [3, 2, 3, 1, 3, 1, 1, 2, 3, 3]])

In [19]:
b= a[a[:, 2] == 4]
print(b)
print(b.shape)

[[2 2 4 4 2 4 4 1 2 1]
 [1 3 4 4 1 1 1 2 3 3]
 [2 3 4 4 1 2 2 1 3 3]
 [3 3 4 3 2 1 3 1 1 2]]
(4, 10)
