# Conditional selection

In [1]:
import numpy as np

In [10]:
a = np.random.randint(2, 10, size =(10,10))
a

array([[6, 9, 3, 9, 7, 3, 7, 5, 9, 4],
       [5, 9, 8, 5, 6, 2, 8, 5, 9, 6],
       [2, 9, 4, 5, 2, 2, 7, 5, 3, 2],
       [4, 5, 9, 8, 2, 7, 8, 2, 8, 3],
       [8, 8, 2, 8, 9, 2, 8, 7, 4, 9],
       [6, 2, 4, 8, 7, 2, 2, 2, 5, 9],
       [7, 9, 4, 6, 4, 8, 3, 8, 2, 9],
       [3, 7, 4, 8, 5, 2, 8, 6, 7, 8],
       [5, 4, 2, 6, 3, 8, 7, 7, 6, 4],
       [8, 6, 4, 2, 8, 5, 3, 2, 7, 7]])

In [11]:
b = a > 2
b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [ True,  True,  True,  True, False,  True,  True, False,  True,
         True],
       [ True,  True, False,  True,  True, False,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True, False, False, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True, False,  True,
         True]])

In [12]:
a[a>3]

array([6, 9, 9, 7, 7, 5, 9, 4, 5, 9, 8, 5, 6, 8, 5, 9, 6, 9, 4, 5, 7, 5,
       4, 5, 9, 8, 7, 8, 8, 8, 8, 8, 9, 8, 7, 4, 9, 6, 4, 8, 7, 5, 9, 7,
       9, 4, 6, 4, 8, 8, 9, 7, 4, 8, 5, 8, 6, 7, 8, 5, 4, 6, 8, 7, 7, 6,
       4, 8, 6, 4, 8, 5, 7, 7])

In [13]:
a[a%2==0]

array([6, 4, 8, 6, 2, 8, 6, 2, 4, 2, 2, 2, 4, 8, 2, 8, 2, 8, 8, 8, 2, 8,
       2, 8, 4, 6, 2, 4, 8, 2, 2, 2, 4, 6, 4, 8, 8, 2, 4, 8, 2, 8, 6, 8,
       4, 2, 6, 8, 6, 4, 8, 6, 4, 2, 8, 2])

In [16]:
two = a[a==2]

In [17]:
#Number of elements
two.shape

(18,)