# Iteration of arrays

In [1]:
import numpy as np

## 1-D array

In [2]:
arr = np.array([1, 2, 3])

In [3]:
#Iterate each element of the array
for x in arr:
    print(x)

1
2
3


## 2-D array

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
#Iterate each line (row) but not each element
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [10]:
#Iterate each element
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


## 3-D array

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [13]:
#Iterate each matrix but not each element
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [14]:
#Iterate each line (row) but not each element
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [15]:
#Iterate each element
for x in arr:
     for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
1
2
3
4
5
6
