# Joining arrays (concatenation)

In [1]:
import numpy as np

## 1-D arrays

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

final = np.concatenate((arr1, arr2))
final

array([1, 2, 3, 4, 5, 6])

## 2-D arrays

In [7]:
arr1 = np.array([[1,2,3], [1,2,3]])
arr2 = np.array([[4,5,6], [4,5,6]])

final = np.concatenate((arr1, arr2))
final

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

## 3-D arrays

In [8]:
arr1 = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
arr2 = np.array([[[4,5,6], [4,5,6]], [[4,5,6], [4,5,6]]])

final = np.concatenate((arr1, arr2))
final

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]],

       [[4, 5, 6],
        [4, 5, 6]]])