In [1]:
import numpy as np

# Basics

## Initialize an array

### One dimensional

In [2]:
a = np.array([1,2,3])
print(a)

## Transponse

In [54]:
a.transpose()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Bidimensional array

In [51]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Get the dimensions

In [5]:
a.ndim

1

### Get shape

In [6]:
b.shape

(3, 3)

### Get type

In [7]:
a.dtype

dtype('int64')

### Get Size

In [9]:
#Return the number of bytes
print(a.itemsize)
print(b.itemsize)

8
8


### Get total size (in number of bytes)

In [10]:
a.size * a.itemsize
#or
a.nbytes

24

# Accesing to a specific element, row, column

In [12]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
#Get a specific element
a[1,5]

#Negative notation similar to list
a[1,-2]


13

### Get a specific row

In [15]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

### Get a specific column

In [16]:
a[: ,1]

array([2, 9])

In [17]:
#Fancy research
a[0, 1:4]

array([2, 3, 4])

## Changing the value of an array

In [19]:
a[1,2] = 4

a[0,:] = 2
a

array([[ 2,  2,  2,  2,  2,  2,  2],
       [ 8,  9,  4, 11, 12, 13, 14]])

# 3D example

In [21]:
b =  np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Get a specific element 

In [23]:
# 0 is the layer, the firsr 1 is the x and the second 1 is the y 
b[0,1,1]


4

### Replace values

In [25]:
b[0,1,1] = 2
b[0,1,1]

#Modify the column line 1 (the second) of each layer
b[:,1,:] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# initializing different types of Arrays

In [28]:
# All 0s matrix 
np.zeros((5,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
# All 1s matrix
np.ones((4,2,2), dtype="int") #Using dtype you eliminate each floating number

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
#Any other number matrix with the same numbers
np.full((2,2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

### Random decimal numbers

In [36]:
#With floating numbers
np.random.rand(4,2,3)

array([[[0.43409143, 0.70520667, 0.10023347],
        [0.47383939, 0.06644196, 0.38395139]],

       [[0.08390284, 0.07845815, 0.08418425],
        [0.08279306, 0.76529004, 0.11946511]],

       [[0.20332085, 0.07714437, 0.68081219],
        [0.27228176, 0.79751015, 0.85375935]],

       [[0.61118666, 0.40230781, 0.45596453],
        [0.5427669 , 0.60868349, 0.93401516]]])

In [39]:
#With int numbers
#First is the minimum
#Second is the maximum
np.random.randint(4,7, size=(4,2,3))

array([[[5, 5, 6],
        [5, 5, 4]],

       [[4, 4, 4],
        [5, 5, 5]],

       [[6, 4, 5],
        [6, 5, 4]],

       [[6, 5, 4],
        [5, 6, 5]]])

In [40]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Operations between matrix

In [48]:
a = np.identity(5)
b = np.full((5,5), 4)


## Product

In [47]:
c = np.matmul(a,b)
c

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

## Sum

In [44]:
c = a+b
c

array([[5., 4., 4., 4., 4.],
       [4., 5., 4., 4., 4.],
       [4., 4., 5., 4., 4.],
       [4., 4., 4., 5., 4.],
       [4., 4., 4., 4., 5.]])

## Determinant

In [50]:
c = np.identity(3)
np.linalg.det(c)

1.0

# Stats

In [52]:
#Max and min
np.min(c)
np.max(c)

1.0

# Read data from file

In [56]:
np.genfromtxt("data.txt", delimiter=',')

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])