# Operations in Numpy with matrixs

In [2]:
import numpy as np

## Product with matrix

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 

In [9]:
# Scalar product
np.dot(2,b)

array([[10, 12],
       [14, 16]])

In [11]:
#Product between matrixs
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

## Transpose

In [21]:
a = np.array([[1,2], [3,4], [5,6]])
np.transpose(a)


array([[1, 3, 5],
       [2, 4, 6]])

## Trace

In [23]:
trace = a.trace()
print(trace)

5


## Rank

In [25]:
a = np.array([[1,2], [3,4]])
det = np.linalg.det(a)
print(det)

2


## Determinant

In [27]:
a = np.array([[1,2], [3,4]])
det = np.linalg.det(a)
print(det)

-2.0000000000000004


# Eigenvalues and eigenvectors

## Eigenvalues

In [29]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [32]:
eigenvalues, eigenvector = np.linalg.eig(a)


In [33]:
eigenvalues

array([-0.37228132,  5.37228132])

In [34]:
eigenvector

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])